export const collectionsData = {
  hoodies: {
    title: 'Hoodies',
    description:
      'Premium coats designed to keep you warm and stylish during the colder months.',
    items: [
      {
        id: '1',
        name: 'Classic Black Hoodie',
        price: '₹498.00',
        originalPrice: '₹688.00',
        discount: '6% OFF',
        description:
          "Our men's brown long coat is the perfect addition to any gentleman's wardrobe. Made with high-quality materials, this coat is designed to keep you warm and stylish during the colder months. The classic brown color and timeless design make it a versatile piece that can be dressed up or down for any occasion.",
        features: [
          'High-quality materials for durability and comfort',
          'Classic notch lapel collar and single-breasted button closure',
          'Two front pockets for convenient storage or hand warming',
          'Long length provides excellent coverage and warmth',
          'Flattering fit for all body types',
        ],
        colors: ['coffee', 'darkbrown', 'olive', 'tan', 'black'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 5.0,
        reviews: 1,
        images: ['/images/collections/hoodies/hoodie-black.webp'],
      },
      {
        id: '2',
        name: 'Classic Lavender Hoodie',
        price: '₹498.00',
        originalPrice: '₹688.00',
        discount: '6% OFF',
        description:
          "Our men's brown long coat is the perfect addition to any gentleman's wardrobe. Made with high-quality materials, this coat is designed to keep you warm and stylish during the colder months. The classic brown color and timeless design make it a versatile piece that can be dressed up or down for any occasion.",
        features: [
          'High-quality materials for durability and comfort',
          'Classic notch lapel collar and single-breasted button closure',
          'Two front pockets for convenient storage or hand warming',
          'Long length provides excellent coverage and warmth',
          'Flattering fit for all body types',
        ],
        colors: ['coffee', 'darkbrown', 'olive', 'tan', 'black'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 5.0,
        reviews: 1,
        images: ['/images/collections/hoodies/hoodie-lavender.webp'],
      },
      {
        id: '3',
        name: 'Classic Navy Hoodie',
        price: '₹498.00',
        originalPrice: '₹688.00',
        discount: '6% OFF',
        description:
          "Our men's brown long coat is the perfect addition to any gentleman's wardrobe. Made with high-quality materials, this coat is designed to keep you warm and stylish during the colder months. The classic brown color and timeless design make it a versatile piece that can be dressed up or down for any occasion.",
        features: [
          'High-quality materials for durability and comfort',
          'Classic notch lapel collar and single-breasted button closure',
          'Two front pockets for convenient storage or hand warming',
          'Long length provides excellent coverage and warmth',
          'Flattering fit for all body types',
        ],
        colors: ['coffee', 'darkbrown', 'olive', 'tan', 'black'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 5.0,
        reviews: 1,
        images: ['/images/collections/hoodies/hoodie-navy.webp'],
      },
      {
        id: '4',
        name: 'Classic Olive Green Hoodie',
        price: '₹498.00',
        originalPrice: '₹688.00',
        discount: '6% OFF',
        description:
          "Our men's brown long coat is the perfect addition to any gentleman's wardrobe. Made with high-quality materials, this coat is designed to keep you warm and stylish during the colder months. The classic brown color and timeless design make it a versatile piece that can be dressed up or down for any occasion.",
        features: [
          'High-quality materials for durability and comfort',
          'Classic notch lapel collar and single-breasted button closure',
          'Two front pockets for convenient storage or hand warming',
          'Long length provides excellent coverage and warmth',
          'Flattering fit for all body types',
        ],
        colors: ['coffee', 'darkbrown', 'olive', 'tan', 'black'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 5.0,
        reviews: 1,
        images: ['/images/collections/hoodies/hoodie-olive1.webp'],
      },
      {
        id: '5',
        name: 'Classic Verdigris Blue Hoodie',
        price: '₹489.99',
        originalPrice: '₹209.99',
        discount: '10% OFF',
        description:
          'A timeless trench coat that never goes out of style. Perfect for transitional weather and professional settings.',
        features: [
          'Water-resistant fabric',
          'Adjustable belt',
          'Interior pockets',
          'Classic double-breasted design',
          'Removable liner for seasonal versatility',
        ],
        colors: ['beige', 'black', 'navy'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 4.8,
        reviews: 24,
        images: ['/images/collections/hoodies/hoodie-olive.webp'],
      },
    ],
  },
  tshirts: {
    title: 'T-Shirts',
    description:
      'Explore our range of stylish t-shirts in various colors and designs.',
    items: [
      {
        id: '1',
        name: 'Basic White T-Shirt',
        price: '₹239',
        originalPrice: '₹699',
        discount: '20% OFF',
        description:
          'A comfortable and versatile white t-shirt made from premium cotton.',
        features: [
          '100% organic cotton',
          'Breathable fabric',
          'Regular fit',
          'Crew neck',
          'Easy to style',
        ],
        colors: ['white', 'black', 'gray', 'navy', 'red'],
        sizes: ['XS', 'S', 'M', 'L', 'XL'],
        rating: 4.5,
        reviews: 42,
        images: ['/images/collections/tshirts/tshirt-graphic.webp'],
      },
      {
        id: '2',
        name: 'Graphic Tee',
        price: '₹239',
        originalPrice: '₹699',
        discount: '13% OFF',
        description:
          'Express your personality with our unique graphic tee designs.',
        features: [
          'Soft cotton blend',
          'Durable print',
          'Pre-shrunk fabric',
          'Relaxed fit',
          'Unisex design',
        ],
        colors: ['black', 'white', 'gray'],
        sizes: ['S', 'M', 'L', 'XL'],
        rating: 4.7,
        reviews: 18,
        images: ['/images/collections/tshirts/tshirt-graphic.webp'],
      },
    ],
  },
  sweatshirts: {
    title: 'Sweat-Shirts',
    description:
      'Find the best Sweat-Shirt for work, casual, and formal occasions.',
    items: [
      {
        id: '1',
        name: 'Slim lavender Sweat-Shirt',
        price: '₹4999',
        originalPrice: '₹5999',
        discount: '17% OFF',
        description:
          'Elegant slim fit sweat-shirt perfect for formal and business occasions.',
        features: [
          'Wrinkle-resistant fabric',
          'Slim fit design',
          'Hidden stretch for comfort',
          'Side and back pockets',
          'Belt loops',
        ],
        colors: ['black', 'navy', 'charcoal', 'beige'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.6,
        reviews: 35,
        images: ['/images/collections/sweatshirts/sweatshirt-lavender.webp'],
      },
      {
        id: '2',
        name: 'Slim Powder Blue Sweat-Shirt',
        price: '₹3999',
        originalPrice: '₹4599',
        discount: '13% OFF',
        description:
          'Versatile sweat-shirt that transition seamlessly from casual to semi-formal settings.',
        features: [
          'Cotton twill fabric',
          'Regular fit',
          'Flat front design',
          'Slash pockets',
          'Versatile styling options',
        ],
        colors: ['gray', 'navy', 'blue', 'burgundy', 'tan'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.4,
        reviews: 27,
        images: ['/images/collections/sweatshirts/sweatshirt-powder-blue.webp'],
      },
      {
        id: '3',
        name: 'Slim Sweat-Shirt',
        price: '₹2999',
        originalPrice: '₹4599',
        discount: '13% OFF',
        description:
          'Sweat-shirt that transition seamlessly from casual to semi-formal settings.',
        features: [
          'Cotton twill fabric',
          'Regular fit',
          'Flat front design',
          'Slash pockets',
          'Versatile styling options',
        ],
        colors: ['gray', 'navy', 'blue', 'burgundy', 'tan'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.4,
        reviews: 27,
        images: ['/images/collections/sweatshirts/sweatshirt-mocha.webp'],
      },
      {
        id: '4',
        name: 'Slim Sweat-Shirt',
        price: '₹1999',
        originalPrice: '₹4599',
        discount: '13% OFF',
        description:
          'Versatile sweat-shirt that transition seamlessly from casual to semi-formal settings.',
        features: [
          'Cotton twill fabric',
          'Regular fit',
          'Flat front design',
          'Slash pockets',
          'Versatile styling options',
        ],
        colors: ['gray', 'navy', 'blue', 'burgundy', 'tan'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.4,
        reviews: 27,
        images: ['/images/collections/sweatshirts/sweatshirt-navy-blue.webp'],
      },
      {
        id: '5',
        name: 'Slim Sweat-Shirt',
        price: '₹2999',
        originalPrice: '₹4599',
        discount: '13% OFF',
        description:
          'Versatile sweat-shirt that transition seamlessly from casual to semi-formal settings.',
        features: [
          'Cotton twill fabric',
          'Regular fit',
          'Flat front design',
          'Slash pockets',
          'Versatile styling options',
        ],
        colors: ['gray', 'navy', 'blue', 'burgundy', 'tan'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.4,
        reviews: 27,
        images: ['/images/collections/sweatshirts/sweatshirt-mocha.webp'],
      },
      {
        id: '6',
        name: 'Slim Sweat-Shirt',
        price: '₹999',
        originalPrice: '₹1599',
        discount: '13% OFF',
        description:
          'Sweat-shirt that transition seamlessly from casual to semi-formal settings.',
        features: [
          'Cotton twill fabric',
          'Regular fit',
          'Flat front design',
          'Slash pockets',
          'Versatile styling options',
        ],
        colors: ['gray', 'navy', 'blue', 'burgundy', 'tan'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.4,
        reviews: 27,
        images: ['/images/collections/sweatshirts/sweatshirt-lavender.webp'],
      },
    ],
  },
  cargos: {
    title: 'Cargos & Joggers',
    description: 'Comfortable and stylish pants for every occasion.',
    items: [
      {
        id: '1',
        name: 'Jordan Joggers',
        price: '₹599',
        originalPrice: '₹899',
        discount: '14% OFF',
        description:
          'Classic jogger with a modern fit and premium quality construction.',
        features: [
          'Premium cotton fabric',
          'Straight leg fit',
          'Five-pocket design',
          'Reinforced stitching',
          'Versatile styling options',
        ],
        colors: ['blue', 'black', 'gray', 'light-wash'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.8,
        reviews: 56,
        images: [
          '/images/joggers-collections/jogger-1.jpeg',
          '/images/joggers-collections/jogger-14.jpeg',
          '/images/joggers-collections/jogger-15.jpeg',
        ],
      },
      {
        id: '2',
        name: 'Urban Glide Joggers',
        price: '₹499',
        originalPrice: '₹599',
        discount: '18% OFF',
        description:
          'Functional jogger with multiple pockets for practicality and style.',
        features: [
          'Durable cotton blend',
          'Multiple pockets',
          'Relaxed fit',
          'Adjustable waistband',
          'Reinforced knees',
        ],
        colors: ['olive', 'khaki', 'black', 'gray', 'navy'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.3,
        reviews: 31,
        images: [
          '/images/joggers-collections/jogger-15.jpeg',
          '/images/joggers-collections/jogger-1.jpeg',
        ],
      },
      {
        id: '3',
        name: 'HyperFlex Jogger',
        price: '₹459',
        originalPrice: '₹559',
        discount: '18% OFF',
        description:
          'Functional cargo pants with multiple pockets for practicality and style.',
        features: [
          'Durable cotton blend',
          'Multiple cargo pockets',
          'Relaxed fit',
          'Adjustable waistband',
          'Reinforced knees',
        ],
        colors: ['olive', 'khaki', 'black', 'gray', 'navy'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.3,
        reviews: 31,
        images: ['/images/joggers-collections/jogger-5.webp'],
      },
      {
        id: '4',
        name: 'Sanc Street Jogger',
        price: '₹599',
        originalPrice: '₹799',
        discount: '18% OFF',
        description:
          'Functional cargo pants with multiple pockets for practicality and style.',
        features: [
          'Durable cotton blend',
          'Multiple cargo pockets',
          'Relaxed fit',
          'Adjustable waistband',
          'Reinforced knees',
        ],
        colors: ['olive', 'khaki', 'black', 'gray', 'navy'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.3,
        reviews: 31,
        images: ['/images/joggers-collections/jogger-8.webp'],
      },
      {
        id: '5',
        name: 'Candies Luxe Joggers',
        price: '₹499',
        originalPrice: '₹699',
        discount: '8% OFF',
        description:
          'Functional cargo pants with multiple pockets for practicality and style.',
        features: [
          'Durable cotton blend',
          'Multiple cargo pockets',
          'Relaxed fit',
          'Adjustable waistband',
          'Reinforced knees',
        ],
        colors: ['olive', 'khaki', 'black', 'gray', 'navy'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.3,
        reviews: 31,
        images: ['/images/joggers-collections/jogger-9.webp'],
      },
      {
        id: '6',
        name: 'SprintX Joggers',
        price: '₹399',
        originalPrice: '₹699',
        discount: '28% OFF',
        description:
          'Functional cargo pants with multiple pockets for practicality and style.',
        features: [
          'Durable cotton blend',
          'Multiple cargo pockets',
          'Relaxed fit',
          'Adjustable waistband',
          'Reinforced knees',
        ],
        colors: ['olive', 'khaki', 'black', 'gray', 'navy'],
        sizes: ['28', '30', '32', '34', '36', '38'],
        rating: 4.3,
        reviews: 31,
        images: ['/images/joggers-collections/jogger-13.jpeg'],
      },
    ],
  },
  jackets: {
    title: 'Jackets',
    description:
      'Premium coats designed to keep you warm and stylish during the colder months.',
    items: [
      {
        id: '1',
        name: 'Street Luxe Hoodie',
        price: 1199.0,
        originalPrice: 1350.0,
        discount: '6% OFF',
        description:
          "Our men's brown long coat is the perfect addition to any gentleman's wardrobe. Made with high-quality materials, this coat is designed to keep you warm and stylish during the colder months. The classic brown color and timeless design make it a versatile piece that can be dressed up or down for any occasion.",
        features: [
          'High-quality materials for durability and comfort',
          'Classic notch lapel collar and single-breasted button closure',
          'Two front pockets for convenient storage or hand warming',
          'Long length provides excellent coverage and warmth',
          'Flattering fit for all body types',
        ],
        colors: ['coffee', 'darkbrown', 'olive', 'tan', 'black'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 5.0,
        reviews: 421,
        images: ['/images/esf-clothes/esf-hoodie-5.jpeg'],
      },
      {
        id: '2',
        name: 'Midnight Glow Hoodie ',
        price: '1499.00',
        originalPrice: '₹1199.00',
        discount: '6% OFF',
        description:
          "Brighten up your streetwear game with the Midnight Glow Hoodie—a bold fusion of comfort and style in an eye-catching neon green shade. Whether you're hitting the streets or lounging indoors, this hoodie guarantees a standout look with its minimalist yet vibrant design. ",
        features: [
          'Striking Neon Glow – A fresh, bold color that grabs attention.',
          'Ultra-Soft Fabric – Crafted for all-day comfort and warmth.',
          'Classic Kangaroo Pocket – Perfect for utility and style.',
          'Adjustable Hood & Ribbed Cuffs – A snug fit with added coziness.',
        ],
        colors: ['coffee', 'darkbrown', 'olive', 'tan', 'black'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 5.0,
        reviews: 231,
        images: ['/images/esf-clothes/esf-hoodie-1.webp'],
      },
      {
        id: '3',
        name: 'Slate Street Hoodie',
        price: '1455.0',
        originalPrice: '₹1999.00',
        discount: '6% OFF',
        description:
          'A modern classic, the Slate Street Hoodie is designed for those who appreciate a clean, minimalist look with maximum comfort. The soft heather gray shade makes it a versatile wardrobe staple, perfect for casual outings or layering up in style.',
        features: [
          ' Timeless Slate Gray – A neutral tone that pairs effortlessly with any outfit.',
          'Premium Fabric Blend – Ultra-soft, breathable, and warm.',
          'Classic Hoodie Fit – Ribbed cuffs, adjustable drawstrings, and a relaxed silhouette.',
          'Functional Kangaroo Pocket – For added convenience and coziness.',
        ],
        colors: ['coffee', 'darkbrown', 'olive', 'tan', 'black'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 5.0,
        reviews: 109,
        images: ['/images/esf-clothes/esf-hoodie-2.jpg'],
      },
      {
        id: '4',
        name: 'The Hype Tee',
        price: '₹480.0',
        originalPrice: '₹550.0',
        discount: '18% OFF',
        description:
          "Our men's brown long coat is the perfect addition to any gentleman's wardrobe. Made with high-quality materials, this coat is designed to keep you warm and stylish during the colder months. The classic brown color and timeless design make it a versatile piece that can be dressed up or down for any occasion.",
        features: [
          'High-quality materials for durability and comfort',
          'Classic notch lapel collar and single-breasted button closure',
          'Two front pockets for convenient storage or hand warming',
          'Long length provides excellent coverage and warmth',
          'Flattering fit for all body types',
        ],
        colors: ['coffee', 'darkbrown', 'olive', 'tan', 'black'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 5.0,
        reviews: 1,
        images: ['/images/esf-clothes/esf-tshirt-3.jpeg'],
      },
      {
        id: '5',
        name: 'ShadowFlex Tee',
        price: '₹588.0',
        originalPrice: '₹1199.00',
        discount: '16% OFF',
        description:
          "Our men's brown long coat is the perfect addition to any gentleman's wardrobe. Made with high-quality materials, this coat is designed to keep you warm and stylish during the colder months. The classic brown color and timeless design make it a versatile piece that can be dressed up or down for any occasion.",
        features: [
          'High-quality materials for durability and comfort',
          'Classic notch lapel collar and single-breasted button closure',
          'Two front pockets for convenient storage or hand warming',
          'Long length provides excellent coverage and warmth',
          'Flattering fit for all body types',
        ],
        colors: ['coffee', 'darkbrown', 'olive', 'tan', 'black'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 5.0,
        reviews: 110,
        images: ['/images/esf-clothes/esf-tshirt-2.jpeg'],
      },
      {
        id: '6',
        name: 'Tiger Strike T-Shirt',
        price: '₹2360.00',
        originalPrice: '₹3199.00',
        discount: '6% OFF',
        description:
          "Our men's brown long coat is the perfect addition to any gentleman's wardrobe. Made with high-quality materials, this coat is designed to keep you warm and stylish during the colder months. The classic brown color and timeless design make it a versatile piece that can be dressed up or down for any occasion.",
        features: [
          'High-quality materials for durability and comfort',
          'Classic notch lapel collar and single-breasted button closure',
          'Two front pockets for convenient storage or hand warming',
          'Long length provides excellent coverage and warmth',
          'Flattering fit for all body types',
        ],
        colors: ['coffee', 'darkbrown', 'olive', 'tan', 'black'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 5.0,
        reviews: 21,
        images: ['/images/esf-clothes/esf-tshirt-1.jpeg'],
      },
      {
        id: '7',
        name: 'Drip Essential Hoodie',
        price: '₹498.00',
        originalPrice: '₹1199.00',
        discount: '6% OFF',
        description:
          "Our men's brown long coat is the perfect addition to any gentleman's wardrobe. Made with high-quality materials, this coat is designed to keep you warm and stylish during the colder months. The classic brown color and timeless design make it a versatile piece that can be dressed up or down for any occasion.",
        features: [
          'High-quality materials for durability and comfort',
          'Classic notch lapel collar and single-breasted button closure',
          'Two front pockets for convenient storage or hand warming',
          'Long length provides excellent coverage and warmth',
          'Flattering fit for all body types',
        ],
        colors: ['coffee', 'darkbrown', 'olive', 'tan', 'black'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 5.0,
        reviews: 12,
        images: ['/images/esf-clothes/esf-zipper-hoodie-2.jpg'],
      },
      {
        id: '8',
        name: 'Redline Zipper Hoodie',
        price: '₹1248.0',
        originalPrice: '₹1399.00',
        discount: '14% OFF',
        description:
          "Our men's brown long coat is the perfect addition to any gentleman's wardrobe. Made with high-quality materials, this coat is designed to keep you warm and stylish during the colder months. The classic brown color and timeless design make it a versatile piece that can be dressed up or down for any occasion.",
        features: [
          'High-quality materials for durability and comfort',
          'Classic notch lapel collar and single-breasted button closure',
          'Two front pockets for convenient storage or hand warming',
          'Long length provides excellent coverage and warmth',
          'Flattering fit for all body types',
        ],
        colors: ['coffee', 'darkbrown', 'olive', 'tan', 'black'],
        sizes: ['S', 'M', 'L', 'XL', 'XXL'],
        rating: 5.0,
        reviews: 110,
        images: ['/images/esf-clothes/esf-hoodie-5.jpeg'],
      },
    ],
  },
};
